# ================================================
# Render configuration for Django (AIBUDDY project)
# ================================================

services:
  - type: web
    name: aibuddy
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn aibuddy.wsgi:application

    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: aibuddy.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_URL
        sync: false

    healthCheckPath: /
    autoDeploy: true
    plan: free

staticPublishPath: staticfiles
