services:
  - type: web
    name: ai-learning-buddy
    env: python
    rootDir: aibuddy
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aibuddy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
