"""
Django settings for aibuddy project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.management.utils import get_random_secret_key

# ============================================================
# 🔹 Base directory & environment setup
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # Load .env if available

# ============================================================
# 🔹 Security settings
# ============================================================
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# ✅ Render automatically sets RENDER environment variable
DEBUG = os.getenv("DEBUG", "True") == "True"
if os.getenv("RENDER"):
    DEBUG = False  # Disable DEBUG in production automatically

ALLOWED_HOSTS = [
    "*",  # allows all for now (you can restrict later)
    "127.0.0.1",
    "localhost",
    "ai-learning-buddy-r82b.onrender.com",
]

# ============================================================
# 🔹 External API Keys
# ============================================================
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_API_URL = os.getenv(
    "GROQ_API_URL",
    "https://api.groq.com/openai/v1/chat/completions",
)

# ============================================================
# 🔹 Installed apps
# ============================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chat",
]

# ============================================================
# 🔹 Middleware
# ============================================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ============================================================
# 🔹 URL Configuration
# ============================================================
ROOT_URLCONF = "aibuddy.urls"

# ============================================================
# 🔹 Templates
# ============================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "chat", "templates"),  # ✅ Chat popup HTML location
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aibuddy.wsgi.application"

# ============================================================
# 🔹 Database
# ============================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ============================================================
# 🔹 Password validation
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================
# 🔹 Internationalization
# ============================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ============================================================
# 🔹 Static files (for CSS, JS, Images)
# ============================================================
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# ============================================================
# 🔹 Default primary key field type
# ============================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
